=== nohal/piman_pi/OpenCPNPluginManager.PluginManifest.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
    targetNamespace="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest"
    xmlns="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest"
    xmlns:pluginManifest="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PluginManifest">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pluginManifest:PluginName" minOccurs="1" maxOccurs="1"> </xs:element>
                <xs:element ref="pluginManifest:Description" minOccurs="1" maxOccurs="1"> </xs:element>
                <xs:element ref="pluginManifest:CommonData" minOccurs="0" maxOccurs="unbounded"> </xs:element>
                <xs:element ref="pluginManifest:PlatformData" minOccurs="1" maxOccurs="unbounded"> </xs:element>
                <xs:element ref="pluginManifest:Dependency" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="Version" type="xs:int" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Manifest format version
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Name" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>
                        A plugin system name, such as xxx_pi
                        Will be used to create the directory to store the plug-in, to reference the plug-in in the dependencies, etc.
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="IconUrl" type="xs:anyURI" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        URL of the icon image - PNG, 32x32px
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="ScreenshotUrl" type="xs:anyURI" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        URL of the screenshot image, PNG
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="HomepageUrl" type="xs:anyURI" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        URL of the plug-in website
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Author" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Author name
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="ReleaseDate" type="xs:dateTime" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Release date
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="VersionMajor" type="xs:int" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Major version number
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="VersionMinor" type="xs:int" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Minor version number
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="APILevelMajor" type="xs:int" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Major API Version needed by this version of the plug-in
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="APILevelMinor" type="xs:int" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Minor API Version needed by this version of the plug-in
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="PluginName">
        <xs:annotation>
            <xs:documentation>
                The human readable name of the plugin, such as "Climatology"
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="Description">
        <xs:annotation>
            <xs:documentation>
                Plugin description text
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="CommonData">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>
                    Location of a file with platform independent part of the plugin, typically data, documentation, etc.
                </xs:documentation>
            </xs:annotation>
            <xs:all>
                <xs:element ref="pluginManifest:PostInstallMessage" minOccurs="0" maxOccurs="1">
                </xs:element>
            </xs:all>
            <xs:attribute name="Url" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Download URL
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Size" type="xs:int" use="required">
                <xs:annotation>
                    <xs:documentation>
                        File size in bytes
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Checksum" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>
                        MD5 checksum
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Description" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Short description of the component (shown to the user)
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Type" type="pluginManifest:DependencyType" use="required"> </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="PostInstallMessage">
        <xs:annotation>
            <xs:documentation>
                Text to show to the user after the installation task is completed
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="PlatformData">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pluginManifest:PostInstallAction" minOccurs="0"
                    maxOccurs="unbounded"> </xs:element>
                <xs:element ref="pluginManifest:PostInstallMessage" minOccurs="0" maxOccurs="1">
                </xs:element>
            </xs:sequence>
            <xs:attribute name="Platform" type="pluginManifest:Platform" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Platform
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Url" type="xs:anyURI" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Download URL
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Size" type="xs:int" use="required">
                <xs:annotation>
                    <xs:documentation>
                        File size in bytes
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Checksum" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>
                        MD5 Checksum
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Description" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Short description of the component (shown to the user)
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="Type" type="pluginManifest:DependencyType" use="required"> </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="Platform">
        <xs:annotation>
            <xs:documentation>
                Supported platform identifier
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Windows"/>
            <xs:enumeration value="Linux32"/>
            <xs:enumeration value="Linux64"/>
            <xs:enumeration value="Mac"/>
            <xs:enumeration value="LinuxArmHf"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="PostInstallAction">
        <xs:annotation>
            <xs:documentation>
                Command to be executed after the installation is finished
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="Dependency">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation>
                    Dependency on another plug-in
                    The element value is PluginManifest.Name of the plug-in on which we depend
                </xs:documentation>
            </xs:annotation>
            <xs:attribute name="Type" type="pluginManifest:DependencyType" use="required"> </xs:attribute>
            <xs:attribute name="Plugin" type="xs:string" use="required"> </xs:attribute>
            <xs:attribute name="MinimalVersionMajor" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Minimal required major version of the dependency
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
            <xs:attribute name="MinimalVersionMinor" type="xs:string" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Minimal required minor version of the dependency
                    </xs:documentation>
                </xs:annotation>

            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="DependencyType">
        <xs:annotation>
            <xs:documentation>
                Type of the dependency
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Recommended"/>
            <xs:enumeration value="Required"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== nohal/piman_pi/sample_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<PluginManifest xmlns="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest OpenCPNPluginManager.PluginManifest.xsd"
 Version="1"
 Name="test_pi"
 IconUrl="http://www.tempuri.org/32x32.png"
 ScreenshotUrl="http://www.tempuri.org/screenshot.png"
 HomepageUrl="http://www.tempuri.org/"
 Author="Author1"
 ReleaseDate="2006-05-04T18:13:51.0"
 VersionMajor="1"
 VersionMinor="1"
 APILevelMajor="1"
 APILevelMinor="10">
    <PluginName>Test Plug-in</PluginName>
    <Description>This is a description of the plug-in</Description>
    <CommonData Url="http://www.tempuri.org/data.xz" Size="100000" Checksum="ec727fd34069730a61cd0a86027989c2">
        <PostInstallMessage>Plug-in was successfully installed</PostInstallMessage>
    </CommonData>
    <CommonData Url="http://www.tempuri.org/data1.xz" Size="100000" Checksum="ec727fd34069730a61cd0a86027989c2" Description="More detailed data"/>
    <PlatformData Platform="Windows" Url="http://www.tempuri.org/win.xz" Size="10000" Checksum="ec727fd34069730a61cd0a86027989c2">
        <PostInstallAction>dir C:</PostInstallAction>
        <PostInstallAction>dir D:</PostInstallAction>
        <PostInstallMessage>Running on Windows</PostInstallMessage>
    </PlatformData>
    <PlatformData Platform="Linux32" Url="http://www.tempuri.org/l32.xz" Size="10000" Checksum="ec727fd34069730a61cd0a86027989c2">
        <PostInstallAction>ls -la /</PostInstallAction>
    </PlatformData>
    <PlatformData Platform="Linux64" Url="http://www.tempuri.org/l64.xz" Size="10000" Checksum="ec727fd34069730a61cd0a86027989c2">
        <PostInstallAction>ls -la /</PostInstallAction>
        <PostInstallMessage>Running on 64-bit X86 Linux</PostInstallMessage>
    </PlatformData>
    <PlatformData Platform="LinuxArmHf" Url="http://www.tempuri.org/larmhf.xz" Size="10000" Checksum="ec727fd34069730a61cd0a86027989c2">
        <PostInstallAction>ls -la /</PostInstallAction>
        <PostInstallMessage>Running on ARM Linux</PostInstallMessage>
    </PlatformData>
    <PlatformData Platform="Mac" Url="http://www.tempuri.org/mac.xz" Size="11000" Checksum="ec727fd34069730a61cd0a86027989c2">
        <PostInstallMessage>Running on Mac OS X</PostInstallMessage>
    </PlatformData>
    <Dependency Type="Recommended" Plugin="grib_pi" />
    <Dependency Type="Required" Plugin="dashboard_pi" MinimalVersionMajor="1" MinimalVersionMinor="2"/>
</PluginManifest>

=== nohal/piman_pi/samples/sample_manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<PluginManifest xmlns="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest OpenCPNPluginManager.PluginManifest.xsd"
 Version="1"
 Name="test_pi"
 IconUrl="http://localhost/icon_32x32.png"
 ScreenshotUrl="http://localhost/screenshot_200x150.png"
 HomepageUrl="http://localhost/"
 Author="John Doe Jr."
 ReleaseDate="2006-05-04T18:13:51.0"
 VersionMajor="1"
 VersionMinor="1"
 APILevelMajor="1"
 APILevelMinor="10">
    <PluginName>Test Plug-in</PluginName>
    <Description>This is a description of the plug-in</Description>
    <CommonData Url="http://localhost/data.tar.xz" Size="188" Checksum="25c4de8696df98a431a9a68b1f9707ed" Type="Required">
        <PostInstallMessage>Plug-in was successfully installed</PostInstallMessage>
    </CommonData>
    <CommonData Url="http://localhost/data1.tar.xz" Size="188" Checksum="276a85ef2b38c58073def8e2988227a2" Description="More detailed data" Type="Recommended"/>
    <PlatformData Platform="Linux64" Url="http://localhost/l64.tar.xz" Size="204" Checksum="9e94047b4e857bcaa73ea10515401b02" Type="Required">
        <PostInstallAction>chmod +x binary.bin</PostInstallAction>
        <PostInstallMessage>Running on 64-bit X86 Linux</PostInstallMessage>
    </PlatformData>
</PluginManifest>

=== nohal/piman_pi/samples/sample_manifest2.xml
<?xml version="1.0" encoding="UTF-8"?>
<PluginManifest xmlns="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.opencpn.org/pluginmanager/OpenCPNPluginManager/PluginManifest OpenCPNPluginManager.PluginManifest.xsd"
 Version="1"
 Name="test2_pi"
 IconUrl="http://localhost/32x32_2.png"
 ScreenshotUrl="http://localhost/screenshot_2.png"
 HomepageUrl="http://localhost/"
 Author="Author1"
 ReleaseDate="2006-05-04T18:13:51.0"
 VersionMajor="1"
 VersionMinor="1"
 APILevelMajor="1"
 APILevelMinor="10">
    <PluginName>Test Plug-in</PluginName>
    <Description>This is a description of the plug-in</Description>
    <CommonData Url="http://localhost/data.tar.xz" Size="188" Checksum="25c4de8696df98a431a9a68b1f9707ed" Type="Recommended">
        <PostInstallMessage>Plug-in was successfully installed</PostInstallMessage>
    </CommonData>
    <CommonData Url="http://localhost/data1.tar.xz" Size="188" Checksum="276a85ef2b38c58073def8e2988227a2" Description="More detailed data" Type="Recommended"/>
    <PlatformData Platform="Windows" Url="http://localhost/win.xz" Size="204" Checksum="ec727fd34069730a61cd0a86027989c2" Type="Required">
        <PostInstallMessage>Running on Windows</PostInstallMessage>
    </PlatformData>
    <PlatformData Platform="Linux32" Url="http://localhost/l32.tar.xz" Size="204" Checksum="9e94047b4e857bcaa73ea10515401b02" Type="Required">
        <PostInstallAction>chmod +x binary.bin</PostInstallAction>
    </PlatformData>
    <PlatformData Platform="Linux64" Url="http://localhost/l64.tar.xz" Size="204" Checksum="9e94047b4e857bcaa73ea10515401b02" Type="Required">
        <PostInstallAction>chmod +x binary.bin</PostInstallAction>
        <PostInstallMessage>Running on 64-bit X86 Linux</PostInstallMessage>
    </PlatformData>
    <PlatformData Platform="LinuxArmHf" Url="http://localhost/larmhf.tar.xz" Size="204" Checksum="9e94047b4e857bcaa73ea10515401b02" Type="Required">
        <PostInstallAction>chmod +x binary.bin</PostInstallAction>
        <PostInstallMessage>Running on ARM Linux</PostInstallMessage>
    </PlatformData>
    <PlatformData Platform="Mac" Url="http://localhost/mac.tar.xz" Size="204" Checksum="9e94047b4e857bcaa73ea10515401b02" Type="Required">
        <PostInstallMessage>Running on Mac OS X</PostInstallMessage>
    </PlatformData>
    <Dependency Type="Recommended" Plugin="grib_pi" />
    <Dependency Type="Required" Plugin="dashboard_pi" MinimalVersionMajor="0" MinimalVersionMinor="1"/>
</PluginManifest>
